name: "Build"
on:
  [workflow_dispatch]
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@int
      with:
        egress-policy: audit
    - uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - run: |
        npm i
        npm run all
    - name: Upload coverage reports to Codecov
      if: always()
      uses: codecov/codecov-action@v3
